/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/lSzZvjYmdhM
 */
import {
  CardContent,
  CardTitle,
  CardDescription,
  CardHeader,
  CardFooter,
  Card,
} from "@/components/ui/card";
import Link from "next/link";

export function Project3() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container grid items-center gap-4 px-4 text-center md:px-6">
        <div className="space-y-3 text-center">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
            My Projects
          </h2>
          <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
            Check out some of my recent work.
          </p>
        </div>
        <div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:gap-8">
          <Card>
            <CardContent className="p-6">
              <img
                alt="Cover image"
                className="aspect-[2/1] rounded-lg object-cover"
                height="200"
                src="/placeholder.svg"
                width="400"
              />
            </CardContent>
            <CardHeader className="p-6">
              <CardTitle className="text-xl font-semibold">
                Project One
              </CardTitle>
              <CardDescription>
                This is a description of Project One.
              </CardDescription>
            </CardHeader>
            <CardFooter className="flex justify-end p-6">
              <Link className="btn btn-sm" href="#">
                View
              </Link>
            </CardFooter>
          </Card>
          <Card>
            <CardContent className="p-6">
              <img
                alt="Cover image"
                className="aspect-[2/1] rounded-lg object-cover"
                height="200"
                src="/placeholder.svg"
                width="400"
              />
            </CardContent>
            <CardHeader className="p-6">
              <CardTitle className="text-xl font-semibold">
                Project Two
              </CardTitle>
              <CardDescription>
                This is a description of Project Two.
              </CardDescription>
            </CardHeader>
            <CardFooter className="flex justify-end p-6">
              <Link className="btn btn-sm" href="#">
                View
              </Link>
            </CardFooter>
          </Card>
          <Card>
            <CardContent className="p-6">
              <img
                alt="Cover image"
                className="aspect-[2/1] rounded-lg object-cover"
                height="200"
                src="/placeholder.svg"
                width="400"
              />
            </CardContent>
            <CardHeader className="p-6">
              <CardTitle className="text-xl font-semibold">
                Project Three
              </CardTitle>
              <CardDescription>
                This is a description of Project Three.
              </CardDescription>
            </CardHeader>
            <CardFooter className="flex justify-end p-6">
              <Link className="btn btn-sm" href="#">
                View
              </Link>
            </CardFooter>
          </Card>
          <Card>
            <CardContent className="p-6">
              <img
                alt="Cover image"
                className="aspect-[2/1] rounded-lg object-cover"
                height="200"
                src="/placeholder.svg"
                width="400"
              />
            </CardContent>
            <CardHeader className="p-6">
              <CardTitle className="text-xl font-semibold">
                Project Four
              </CardTitle>
              <CardDescription>
                This is a description of Project Four.
              </CardDescription>
            </CardHeader>
            <CardFooter className="flex justify-end p-6">
              <Link className="btn btn-sm" href="#">
                View
              </Link>
            </CardFooter>
          </Card>
        </div>
      </div>
    </section>
  );
}
