/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/SY0J6uKkG9j
 */
import Link from "next/link"
import { CardContent, Card, CardFooter } from "@/components/ui/card"

export function Projects2() {
  return (
    <section className="w-full py-12">
      <div className="container grid md:grid-cols-2 lg:grid-cols-3 gap-6 items-start">
        <div className="relative group overflow-hidden rounded-lg">
          <Link className="absolute inset-0 z-10" href="#">
            <span className="sr-only">View</span>
          </Link>
          <Card className="w-full aspect-[16/9] overflow-hidden group-hover:scale-105 transition-transform">
            <CardContent className="flex aspect-[16/9] items-center justify-center p-6">
              <img
                alt="Project cover"
                className="aspect-[16/9] object-cover"
                height={281}
                src="/placeholder.svg"
                width={500}
              />
            </CardContent>
          </Card>
          <Card className="absolute inset-0 transform translate-y-full transition-transform group-hover:translate-y-0">
            <CardContent className="grid gap-4 p-4">
              <h3 className="text-lg font-bold">Marketing Website</h3>
              <p className="text-sm leading-none truncate-2 md:truncate-3">
                A stunning website to showcase our products and drive conversions.
              </p>
            </CardContent>
            <CardFooter className="p-4 flex justify-between">
              <div className="flex items-center space-x-2">
                <img
                  alt="Avatar"
                  className="rounded-full overflow-hidden border border-gray-200 w-6 h-6 dark:border-gray-800"
                  height={24}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "24/24",
                    objectFit: "cover",
                  }}
                  width={24}
                />
                <span className="text-sm font-medium">acme_inc</span>
              </div>
              <div className="flex items-center space-x-2">
                <BookmarkIcon className="w-4 h-4" />
                <ChevronRightIcon className="w-4 h-4" />
              </div>
            </CardFooter>
          </Card>
        </div>
        <div className="relative group overflow-hidden rounded-lg">
          <Link className="absolute inset-0 z-10" href="#">
            <span className="sr-only">View</span>
          </Link>
          <Card className="w-full aspect-[16/9] overflow-hidden group-hover:scale-105 transition-transform">
            <CardContent className="flex aspect-[16/9] items-center justify-center p-6">
              <img
                alt="Project cover"
                className="aspect-[16/9] object-cover"
                height={281}
                src="/placeholder.svg"
                width={500}
              />
            </CardContent>
          </Card>
          <Card className="absolute inset-0 transform translate-y-full transition-transform group-hover:translate-y-0">
            <CardContent className="grid gap-4 p-4">
              <h3 className="text-lg font-bold">Internal Dashboard</h3>
              <p className="text-sm leading-none truncate-2 md:truncate-3">
                A powerful dashboard to monitor our internal metrics and KPIs.
              </p>
            </CardContent>
            <CardFooter className="p-4 flex justify-between">
              <div className="flex items-center space-x-2">
                <img
                  alt="Avatar"
                  className="rounded-full overflow-hidden border border-gray-200 w-6 h-6 dark:border-gray-800"
                  height={24}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "24/24",
                    objectFit: "cover",
                  }}
                  width={24}
                />
                <span className="text-sm font-medium">acme_inc</span>
              </div>
              <div className="flex items-center space-x-2">
                <BookmarkIcon className="w-4 h-4" />
                <ChevronRightIcon className="w-4 h-4" />
              </div>
            </CardFooter>
          </Card>
        </div>
        <div className="relative group overflow-hidden rounded-lg">
          <Link className="absolute inset-0 z-10" href="#">
            <span className="sr-only">View</span>
          </Link>
          <Card className="w-full aspect-[16/9] overflow-hidden group-hover:scale-105 transition-transform">
            <CardContent className="flex aspect-[16/9] items-center justify-center p-6">
              <img
                alt="Project cover"
                className="aspect-[16/9] object-cover"
                height={281}
                src="/placeholder.svg"
                width={500}
              />
            </CardContent>
          </Card>
          <Card className="absolute inset-0 transform translate-y-full transition-transform group-hover:translate-y-0">
            <CardContent className="grid gap-4 p-4">
              <h3 className="text-lg font-bold">Mobile App Redesign</h3>
              <p className="text-sm leading-none truncate-2 md:truncate-3">
                A sleek and modern redesign of our mobile app for iOS and Android.
              </p>
            </CardContent>
            <CardFooter className="p-4 flex justify-between">
              <div className="flex items-center space-x-2">
                <img
                  alt="Avatar"
                  className="rounded-full overflow-hidden border border-gray-200 w-6 h-6 dark:border-gray-800"
                  height={24}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "24/24",
                    objectFit: "cover",
                  }}
                  width={24}
                />
                <span className="text-sm font-medium">acme_inc</span>
              </div>
              <div className="flex items-center space-x-2">
                <BookmarkIcon className="w-4 h-4" />
                <ChevronRightIcon className="w-4 h-4" />
              </div>
            </CardFooter>
          </Card>
        </div>
      </div>
    </section>
  )
}


function BookmarkIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m19 21-7-4-7 4V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v16z" />
    </svg>
  )
}


function ChevronRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}
